name: fisika_mobile_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.13.0
  cloud_firestore: 4.7.1
  firebase_auth: 4.6.1
  flutter_svg: ^1.1.2
  persistent_bottom_nav_bar: ^4.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/icons/
  uses-material-design: true
