name: fisika_mobile_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.13.0
  cloud_firestore: 4.7.1
  firebase_auth: 4.6.1
  flutter_svg: ^1.1.2
  persistent_bottom_nav_bar: ^4.0.2
  video_player: 2.6.1
  firebase_storage: 11.2.1
  chewie: 1.5.0
  flutter_screenutil: 5.7.0
  webview_flutter: 2.1.0
  webview_cookie_manager: 2.0.6
  animated_splash_screen: 1.3.0
  shared_preferences: 2.2.0
  get_storage: 2.1.1
  material_design_icons_flutter: 7.0.7296
  image_picker: 1.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-Medium.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf

    - family: Lobster_Two
      fonts:
        - asset: assets/fonts/LobsterTwo-Regular.ttf

  uses-material-design: true
